### ISSUE TITLE
Set `paintInside` default as true when `offset` is defined.

### ISSUE THREAD

**Issue by SrBrahma** [SrBrahma/react-native-shadow-2#13]
I think this would be the behaviour that everybody would like.

When setting an offset, like `[0, 0.5]`, to have a little shadow around and below the component, it would default `paintInside` to true, to automatically paint the gap between the shadow start on the bottom side, and the corresponding component side, without having to set the `paintInside` all the time.

If someone find a cool visual case to have the gap between the offsetted shadow and the component, this person can just overwrite this default, with `paintInside: false`.

When not using `offset`, `paintInside` will keep its default to `false`, so it won't render the svg part that the user can't see, being the component opaque, saving some performance, battery life etc.

I will probably major it to avoid unexpected visuals.

**Comment by SrBrahma** [comment]
Along with this major, rename ShadowI exported type to ShadowProps. Also, give a hint in README that the user may create presets with this ShadowProps and then `<Shadow {...shadow1}>`. I thought about having predefines in the package, so one could just <Shadow preset='near1'> for example, but as I ain't certain on how to call them and their values, this {...shadow} seems to be a better solution

**Comment by jimmi-joensson** [comment]
@SrBrahma Great suggestion about setting `paintInside: true` as default.
Also what is the reason for `viewStyle` to be of type `ViewStyle` and not `StyleProp<ViewStyle>`?

**Comment by SrBrahma** [comment]
> @SrBrahma Great suggestion about setting `paintInside: true` as default.
> Also what is the reason for `viewStyle` to be of type `ViewStyle` and not `StyleProp<ViewStyle>`?

My ignorance xD

I didn't know about this StyleProp working. Reference for others: https://spin.atomicobject.com/2018/06/02/custom-components-react-native/

Will implement this in the major.

**Comment by jimmi-joensson** [comment]
Well nothing to say about that, also took me some time to realise the difference myself. Only thought there might have been a specific reason for that particular prop, because other places you had used `StyleProp<ViewStyle>` :)

**Comment by SrBrahma** [comment]
> Well nothing to say about that, also took me some time to realise the difference myself. Only thought there might have been a specific reason for that particular prop, because other places you had used `StyleProp<ViewStyle>` :)

Yup! I also found that while working on that yesterday. Looks like I have found that on Google for the containerStyle some time ago, didn't use the same for the viewStyle, and forgot about it.

Now I definitely won't forget it 😅

I will release those changes very soon.

**Comment by SrBrahma** [comment]
All done!
