### ISSUE TITLE
Opacity can't be set for the shadow

### ISSUE THREAD

**Issue by rpulkka** [SrBrahma/react-native-shadow-2#16]
In react-native-shadow, there is props for opacity of the shadow. How can I set the opacity with this package, or is the feature missing altogether?

**Comment by SrBrahma** [comment]
Hi, @rpulkka.

The opacity is set in the startColor and finalColor, in the alpha channel of the color.

A '#0001' color will be an almost transparent black, for example. You may also use 'rgba()', 'hsla()' etc.

**Comment by SrBrahma** [comment]
Also, thanks for the Issue! I have added this question to the FAQ, as there was another Issue in the past that has asked the same.

I understand that as react-native-shadow had it, it is normal to expect this one to have it.

**Comment by rpulkka** [comment]
Thanks a lot! I had not thought that transparency could be added straight into the color notation. With hex color coding the pattern seems to be #rrggbbaa, it works for me. Keep up the good work.

**Comment by SrBrahma** [comment]
Thanks for the encouragement ;)

Yes, this is one of the multiple patterns accepted! Those, except int, are also accepted: https://reactnative.dev/docs/colors. -- I didn't even know that int as color was a thing :open_mouth:

'hsl/a' is very useful! Take a look about it if you don't know it yet. I always recommend it when I can. It was a game changer for me :)
