### ISSUE TITLE
[Opinions Request] Use the SVG only for Android? iOS and Web would use the built-in shadow

### ISSUE THREAD

**Issue by SrBrahma** [SrBrahma/react-native-shadow-2#18]
I had this idea minutes ago, still ain't sure if it would be a good idea, but I think the same appearance would be achievable with better performance and without the web bug, described in readme in bugs session.

**Comment by jimmi-joensson** [comment]
Hmm wouldn't that kinda defeat the purpose of the package? I at least those this package because it gave me one way to define custom shadows across all devices.

**Comment by SrBrahma** [comment]
My point is that I think web and iOS can achieve the exact look as this package, but without using svg, with their built-in shadow. It, as I expect in my idea, wouldn't change the visuals for the users (and devs).

Anyway, I need to test it when I have the time, to see if it is achievable at all.
