### ISSUE TITLE
Use `borderRadius` of `viewStyle`

### ISSUE THREAD

**Issue by rbozan** [SrBrahma/react-native-shadow-2#19]
Awesome library, using it for work right now. One suggestion:

Instead of trying to get the borderRadius of the child, also try to get it of `viewStyle`. Currently I have to write the following:
```jsx
    <Shadow viewStyle={styles.shadowContainer} radius={styles.shadowContainer.borderRadius}>
```

Would be nice if this was automatically done already.

**Comment by SrBrahma** [comment]
Done! Please, test it and report any found bugs!

Added in 4.1.0, via https://github.com/SrBrahma/react-native-shadow-2/commit/b5a0e60fcd06b50354a600dfac66fd26f6f702b2
