### ISSUE TITLE
The offset and size properties are of the wrong type.

### ISSUE THREAD

**Issue by tuxsnct** [SrBrahma/react-native-shadow-2#23]
I don't think TypeScript allows you to specify keys and their types for arrays, but the source code does.

I think it would be better to modify the ShadowProps interface like this:
```typescript
interface ShadowProps {
  // ...
  offset?: (number | string)[];
  // ...
  size?: number[];
  // ...
}
```

Alternatively, you can use the key as follows (not recommended for compatibility reasons):
```typescript
interface ShadowProps {
  // ...
  offset?: { x: number | string, y: number | string };
  // ...
  size?: { width: number, height: number };
  // ...
}
```

**Comment by SrBrahma** [comment]
Hi @tuxsnct! This TS functionality is available since V4, released a year ago. Please, update your typescript version! 🤓

**Comment by SrBrahma** [comment]
They are called *labeled tuples*: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements

**Comment by tuxsnct** [comment]
Oops, looks like it.
Thanks!
