### ISSUE TITLE
Needs to set pointerEvents="box-none"

### ISSUE THREAD

**Issue by AdamSheaHewett** [SrBrahma/react-native-shadow-2#24]
In some cases the shadow HOC will prevent clicks from registering in child components. I've only seen this behavior when shadow is used inside an animated container.

Allowing us to specify props to the container (instead of just styles) would solve this too. pointerEvents is not a valid style, it is a prop on a View.

`pointerEvents="box-none"` will allow clicks to pass through to children without disabling all pointer events.

**Comment by SrBrahma** [comment]
Have you tested this solution by changing the .js lib output files?

I will in a few minutes start dev'ing the other issue there, and I can also add your request.

**Comment by SrBrahma** [comment]
Added it in 5.0.0 via #25. Please, tell me if it's now working properly!

Thanks!
