### ISSUE TITLE
Feature request: add support Animated

### ISSUE THREAD

**Issue by dodiwknd** [SrBrahma/react-native-shadow-2#27]
I am very helpful with this library, thank you in advance.

I hope my request can be realized, if you ask what kind of animation it is, maybe it's more towards making your own `Shdow` component that can be animated by prop or supported by `Animated.createAnimatedComponent`, whether it's from the `Animated API` or `reanimated`

**Comment by SrBrahma** [comment]
What is your use case?

**Comment by dodiwknd** [comment]
> What is your use case?

so far my case is small, like i animate shadow on sticky header, when that scroll event takes place

**Comment by SrBrahma** [comment]
Next time I have free time I will study about it and may do it. Thanks for the suggestion! :)

**Comment by Decezaris** [comment]
The lib has support to add shadow with Animated View? 

I have a progress bar, and I'd like to put shadow to emulate a neon behavior.
