### ISSUE TITLE
Failed build for web

### ISSUE THREAD

**Issue by DrDezmond** [SrBrahma/react-native-shadow-2#29]
Hello, will gladly aprreciete your help.

When trying to build for web, (storybook) I got such an error

ERROR in ./node_modules/react-native-shadow-2/lib/index.js 70:41
Module parse failed: Unexpected token (70:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const [childHeight, setChildHeight] = react_1.useState();
|     /** Defaults to true if offset is defined, else defaults to false */
>     const paintInside = paintInsideProp ?? (offset ? true : false);
|     const [offsetX, offsetY] = offset ?? [0, 0];
|     const distance = R(Math.max(distanceProp, 0)); // Min val as 0
 @ ./src/components/TabNavigation/CustomTabBar/index.tsx 1:753-785
 @ ./src/components/TabNavigation/CustomTabBar/CustomTabBar.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

**Comment by SrBrahma** [comment]
Hmmm... maybe your node version is too old to accept "??"? Are you using typescript?

**Comment by SrBrahma** [comment]
I have updated the tsconfig to have ES6 as target, it should fix your issue. Please, give me your feedback about it after installing the latest version!

Released 5.1.2 via https://github.com/SrBrahma/react-native-shadow-2/commit/284b695102fbd7be1719ef372bc9ee8ca6f257a4

If it hasn't fixed your issue as I think it will, comment here so I can reopen it and give further support.

Thanks for your report! :)

**Comment by DrDezmond** [comment]
@SrBrahma , thanks a lot it helped. I am using ts and node version is 16.9
