### ISSUE TITLE
Implement offsets

### ISSUE THREAD

**Issue by range-of-motion** [SrBrahma/react-native-shadow-2#3]
I'd like to be able to offset my shadows either vertically or horizontally by a few pixels.

**Comment by SrBrahma** [comment]
Ok, will implement it today and write the README ;)

**Comment by SrBrahma** [comment]
But, a question just popped: If the distance is 10, and X is -5, should the distance to the left be 15 or 10?

**Comment by range-of-motion** [comment]
> But, a question just popped: If the distance is 10, and X is -5, should the distance to the left be 15 or 10?

Distance remains 10.

**Comment by SrBrahma** [comment]
Hey, just released it in 1.1.0 (https://github.com/SrBrahma/react-native-shadow-2/commit/a5681fa0b676a484e92785b27eddd2b9fbb2f1d8). Offset won't affect the distance, but moves the entire shadow and draw the content shape with startColor inside the outer shadows.

For now when using offset, it won't work nicely with transparent content you provide (it will have shadow below the content as said in phrase above), as I still haven't found a way to cut it out just below the content. I hope it isn't you case. If it is, tell me and I may focus on that.

Awaiting your feedback about it!

**Comment by SrBrahma** [comment]
Is it working fine?

**Comment by range-of-motion** [comment]
Yea this works great! These buttons down below now have a shadow and I can effectively use the offset prop.

![Screenshot 2021-03-16 at 21 15 27](https://user-images.githubusercontent.com/9268822/111373879-bc790500-869c-11eb-8378-9154bef81672.png)

Thanks so much! 👏

**Comment by SrBrahma** [comment]
Awesome! :)

**Comment by bBSempai** [comment]
> ![Screenshot 2021-03-16 at 21 15 27](https://user-images.githubusercontent.com/9268822/111373879-bc790500-869c-11eb-8378-9154bef81672.png)
@range-of-motion hey how did you control the opacity of the shadow? Is that an option?

**Comment by SrBrahma** [comment]
> > ![Screenshot 2021-03-16 at 21 15 27](https://user-images.githubusercontent.com/9268822/111373879-bc790500-869c-11eb-8378-9154bef81672.png)
> 
> @range-of-motion hey how did you control the opacity of the shadow? Is that an option?
> 
> 
> 

Answered in https://github.com/SrBrahma/react-native-shadow-2/issues/5#issuecomment-813054835
