### ISSUE TITLE
reported a percent.match error, I don't know why

### ISSUE THREAD

**Issue by Fuyun791** [SrBrahma/react-native-shadow-2#35]
![image](https://user-images.githubusercontent.com/52202268/151107937-a0d6af3e-a02a-41b6-9f9e-283e59c9aca2.png)

Step appears
After installation, this problem occurs directly when I write an example in a readme. My package.json is "react-native-shadow-2": "^6.0.1"

**Comment by SrBrahma** [comment]
@Fuyun791 this is probably related to your other issue, the #34, as both errors seems to be a setup error of your project.

What do you mean by "this problem occurs directly when I write an example in a readme"?

Please share here the exact code you are using.

What `react-native-svg` version are you using? And, double check that you fully followed **[its installation instructions](https://github.com/react-native-svg/react-native-svg#installation)**.

**Comment by Fuyun791** [comment]
package.json
    "react-native-shadow-2": "^6.0.1",
    "react-native-svg": "5.5.1",

code:
`
        <Shadow distance={15} startColor={'#eb9066d8'} finalColor={'#ff00ff10'} offset={[3, 4]}>
          <View
            style={{
              borderTopLeftRadius: 24,
              borderBottomRightRadius: 0,
              borderRadius: 10,
              backgroundColor: '#c454f0dd',
            }}
          >
            <TYText style={{ margin: 20, fontSize: 20 }}>🤯</TYText>
          </View>
        </Shadow>
`

**Comment by SrBrahma** [comment]
This react-native-svg version is too old. Please, use the latest one, the v12.

**Comment by Fuyun791** [comment]
Might really be a problem with svg. But I can't upgrade my svg version, sad. Because another package of mine depends on an older version. I can't register both. It seems that I can only use the old react-native-shadow, 😢

**Comment by SrBrahma** [comment]
I see. Unfortunately can't help you further, the react-native-svg@5.5.1 is more than 4 years old 😬

I recommend to use a similar package to the one requiring this old version, if there is one.
