### ISSUE TITLE
Add `stretch` property as shortcut for `viewStyle={{ alignSelf: 'stretch' }}`

### ISSUE THREAD

**Issue by SrBrahma** [SrBrahma/react-native-shadow-2#40]
The `viewStyle={{ alignSelf: 'stretch' }}` is a common practice. Instead of typing all of that, a `stretch` property would improve the DX.

https://github.com/SrBrahma/react-native-shadow-2/issues/7#issuecomment-899784537

**Comment by SrBrahma** [comment]
Added in v7.0.0.

**Comment by Inna-Mykytiuk** [comment]
Sorry, but where i must to erite it? I don't understand it.
<Shadow
          distance={15}
          offset={[0, 4]}
          viewStyle={{ alignSelf: 'stretch' }}
        >
        ??

**Comment by SrBrahma** [comment]
Hi Inna! To use it, do the following:

```tsx
<Shadow
  {...etc} // Other props you may want
  stretch
>
```

The `stretch` property is a shortcut for the `viewStyle={{ alignSelf: 'stretch' }}`, so, it's a quicker way to have this behavior.

Let me know if it is not yet clear!
