### ISSUE TITLE
feature request: integrate the styles at react-native-shadow-2 inside the styled-components

### ISSUE THREAD

**Issue by vagnerwentz** [SrBrahma/react-native-shadow-2#41]

**Comment by vagnerwentz** [comment]
It doesn't integration with styled components just need to do this

```
export const ModalView = styled(Shadow).attrs({
  viewStyle: {
    borderRadius: 8,
    backgroundColor: 'white',
    paddingTop: 25,
    paddingLeft: 24,
    paddingBottom: 24,
    paddingRight: 24,
    width: RFValue(312)
  },
  distance: 10,
  startColor: '#0000001f'
})<ShadowProps>``
```

**Comment by SrBrahma** [comment]
Oi @vagnerwentz!

Não entendi o teu pedido. Está aberto ainda? Pode escrever em português caso tu se sinta mais confortável ;)

**Comment by vagnerwentz** [comment]
Olá @SrBrahma eu não estava conseguindo utilizar os styles da biblioteca dentro do styled components e quis abrir uma issue para fazer uma feature para conseguir, mas aprofundei no styled components e ao utilizar o `.attrs` do styled components há possibilidade de usar sem precisar fazer style inline.

**Comment by SrBrahma** [comment]
Entendi!

Qualquer outra dúvida e/ou sugestão é só dizer 🙂
