### ISSUE TITLE
OPACITY?

### ISSUE THREAD

**Issue by bBSempai** [SrBrahma/react-native-shadow-2#5]
This is great that I do not have to specify the size...BUT IS THERE NO OPACITY SUPPORT?
Also how can I control individual corner radius?

**Comment by SrBrahma** [comment]
Differently to original react-native-shadow, in this one you specify the opacity in the alpha channel of the color you enter in the start/final color property. Ex, `#00000010`, will be a black with a bit of opacity (very transparent)


To specify the radius of each corner, here is how is defined the type:

![IMG_20210404_123825.jpg](https://user-images.githubusercontent.com/28177550/113514021-b57a3f80-9542-11eb-9f71-f1b8fefe8245.jpg)

(`src/index.tsx`, you may want to read it to see other available properties)

I will add it soon to the README. Writing to the README wasn't my focus at the time as I am dev'ing my own project, but as this package is quickly getting somewhat popular, I will improve it.

**Comment by range-of-motion** [comment]
Or use `rgba()` 😉

**Comment by SrBrahma** [comment]
> Or use `rgba()` 😉 

True! It also accepts `'blue'`, `'red'`, `'transparent'` etc. Any color pattern accepted in StyleSheet should work.

**Comment by bBSempai** [comment]
Demn okaay!

**Comment by SrBrahma** [comment]
Feel free to open another issue if you have any question ;)
