### ISSUE TITLE
How to convert Figma design with box-shadow

### ISSUE THREAD

**Issue by chenop** [SrBrahma/react-native-shadow-2#52]
Hi,
I have design requirment to do the following shadow effect
`box-shadow: 0px 3.200000047683716px 20px 0px rgba(0, 0, 0, 0.1);
`

How do I implement it via react-native-shadow-2?

**Comment by SrBrahma** [comment]
There is no direct relation between our Shadow properties and CSS shadow, as better analyzed in #31.

What you can do is just tweak the properties (`distance`, `startColor`, `offset`) until you achieve a similar appearance in what you have in the Figma design.

**Comment by SrBrahma** [comment]
Let me know if you need further help!

**Comment by apperside** [comment]
Most people waits for the judgment day, I am waiting the day that I will be able to make a shadow in react native without losing plenty of hours trying to implement a shadow the same as it is in figma

**Comment by SrBrahma** [comment]
I feel your pain, @apperside! I wish I could help you more but it indeed sucks. Hopefully someone will get into a better solution than me! Maybe WebView? 👀
