### ISSUE TITLE
Web can't support more than 1 shadow.

### ISSUE THREAD

**Issue by GreyJohnsonGit** [SrBrahma/react-native-shadow-2#53]
**Web Only**
My web deployment of a React Native app cannot support more than one linear gradient for `<Shadow>` elements. New `<Shadow>` element gradients simply overwrite all previous gradients. I've fixed it by generating a uuid for each `<Shadow>` and appending it to the id string of each gradient (e.g. ``id={`top.${uuid}`}``, ``fill={`url(#bottomLeft.${uuid})`}``).

1 Shadow:
![image](https://user-images.githubusercontent.com/50259881/178149933-9fe90752-8da5-453e-a29b-abe8afa91693.png)
2 Shadows (notice broken corners): 
![image](https://user-images.githubusercontent.com/50259881/178149879-b195f4d7-82f6-43f2-90ee-5ebf80f5d768.png)
2 Shadows with fix: 
![image](https://user-images.githubusercontent.com/50259881/178149892-3e212ff5-634a-45e2-8ee6-f41aef092a7c.png)

For my sake, let me know if this sounds like a poor solution. Also let me know if you want me to make a PR to add something like this in!

**Comment by SrBrahma** [comment]
Thanks. I will take a look into it asap. The UUID solution makes absolute sense and it's certainly what I would do.

I like the https://github.com/ericelliott/cuid lib for UUID generation, as they use a timestamp and a counter to avoid id colisions. The .slug() would suit it. Maybe a simple counter would also do it.

You may do a PR if you want to, and I would really appreciate it! Else, tell me so I can implement it asap to fix this.

**Comment by SrBrahma** [comment]
Just released it under 6.0.6. Many many thanks!
