### ISSUE TITLE
Support multiple children and follow shape of SVG

### ISSUE THREAD

**Issue by Darhagonable** [SrBrahma/react-native-shadow-2#57]
It would be great if this could behave more like filter shadow in css.

I wanna have a footer with cut out for a FAB. The footer uses two Views and an SVG in the middle for the bit with the cut out.
I want to give the entire thing a shadow that follows the shape of the footer.

Any way this could be possible?

example image:
[https://miro.medium.com/max/1400/1*l41Y0I5SADqrTAy1NBVgTw.png]()

**Comment by SrBrahma** [comment]
Hi @Darhagonable, many thanks for your suggestion!

For your example image, it would be possible if we had the inset (#10) for the inner central part. I've been postergating it for a long while. I will reconsider doing it soon. You would use multiple shadows for each part of this component (maybe 3, 2 for each side and 1 for the inner part).

But, regarding supporting multiple children automatically and following the SVG, I am afraid this isn't possible. The SVG gradient is quite limited: it can only do lines and circles. It wouldn't be possible to follow non-circle curves and different shapes. Also, for multiple children, I don't know if it's possible to make the code smart enough to understand at which sides and corners the shadow should be applied.

Even if I manage to automate your specific case, there will be other cases that it won't work as there are infinite possibilities and problems, I believe.

For your specific case, I recommend using the native Shadow or the https://www.npmjs.com/package/react-native-drop-shadow package, as it gets the resulting view image and apply the shadow around the image.

I will close this as I don't think it's doable. Feel free to contribute with any ideas, though.
