### ISSUE TITLE
[Fixed in 13.6.0] Incompatible with react-native-svg v13.5.0

### ISSUE THREAD

**Issue by chengsokdara** [SrBrahma/react-native-shadow-2#62]
After upgrade react-native-svg to 13.5.0 shadow corners are missing.

<p float="left">
Before
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
After
</p>
<p float="left">
<img alt="Simulator Screen Shot - iPhone 8 Plus - 2022-11-13 at 11 22 57" src="https://user-images.githubusercontent.com/2707253/201505734-3d92310e-1060-453f-bb01-261d159522c8.png" width="200" height="400" />
<img alt="Simulator Screen Shot - iPhone 8 Plus - 2022-11-13 at 11 28 04" src="https://user-images.githubusercontent.com/2707253/201505737-4a87372f-89ad-4002-b88b-ddeb5e45bdb7.png" width="200" height="400" />
</p>

**Comment by alexco2** [comment]
Had the same experience. react-native-svg 13.4.0 still works fine.

**Comment by SrBrahma** [comment]
Thanks for the important report. Tomorrow I will add a note about it on Readme while I don't find it's cause and fix.

**Comment by alexco2** [comment]
Fixed with version 13.6.0

**Comment by SrBrahma** [comment]
Huge thanks, @alexco2!

Updated README with this info and closing this. Please do report any further breaking errors.

**Comment by SrBrahma** [comment]
I will keep this sticked for some time.
