### ISSUE TITLE
Border radius problem

### ISSUE THREAD

**Issue by BenjaminFrancois** [SrBrahma/react-native-shadow-2#64]
Hi,

I've problem on using borderRadius with this code : 
```tsx
    <Shadow
      style={{
        alignSelf: 'stretch',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
      }}
      sides={{ top: true, bottom: false, end: false, start: false }}
    >
      {children}
    </Shadow>
```

Top right corner is cutted

<img width="375" alt="Capture d’écran 2022-12-09 à 22 24 43" src="https://user-images.githubusercontent.com/44391195/206798500-b53315b2-7f71-4eff-a5a6-1d5e6206d89e.png">

Thank's !

**Comment by SrBrahma** [comment]
Can you reproduce it here? https://snack.expo.dev

**Comment by BenjaminFrancois** [comment]
Hello, it's solve with delete build ... my apologies ! 
Thank's !
