### ISSUE TITLE
x-axis offset not working as expected (iOS)

### ISSUE THREAD

**Issue by dmdmd** [SrBrahma/react-native-shadow-2#65]
Hello,

first of all, thank you for this library!

I'm having a hard time controlling the offset x-axis value. It seems that if I simply hardcode values or use them from a state variable, the y-axis works as expected but not the x-axis. I was able to make it work by adding a useEffect (all versions are depicted in the below-mentioned snack).

Here is a snack to reproduce the issue: https://snack.expo.dev/@heyfina-dev/react-native-button-box-shadow

It seems to work on web and android but not on ios. Could you check my snack to see if I'm doing something wrong?

iOS | Web
:------------------------------------:|:------------------------------------:
![image](https://user-images.githubusercontent.com/1687895/211502740-edc44203-b24e-4767-b9a6-a2654043c3f6.png)| ![image](https://user-images.githubusercontent.com/1687895/211340819-87f4d8aa-6246-4420-a6d9-fa43528df6ec.png)

The first element offset is loaded using a state variable + useEffect to set the values.
The second element offset is loaded using a state variable.
The third element offset is hardcoded.

PS: using the `safeRender` prop didn't help

**Comment by SrBrahma** [comment]
This was handled here: https://github.com/SrBrahma/react-native-shadow-2/issues/67

Sorry for the delay and thanks for the report! Should be fixed now in 7.0.7.
