### ISSUE TITLE
could you provide a new prop `blur`？

### ISSUE THREAD

**Issue by SnowingFox** [SrBrahma/react-native-shadow-2#66]
I think `blur` prop can be used to set the blur level of the shadow

**Comment by baesumin** [comment]
+1

**Comment by SrBrahma** [comment]
I have no idea how I would implement this using the current SVG solution; I don't believe this is possible. I will close it, but I can reopen it if a good idea is given.

**Comment by SnowingFox** [comment]
> I have no idea how I would implement this using the current SVG solution; I don't believe this is possible. I will close it, but I can reopen it if a good idea is given.

Maybe we can use canvas solution https://www.npmjs.com/package/react-native-canvas
