### ISSUE TITLE
Inner shadow

### ISSUE THREAD

**Issue by Ali-Oliaee** [SrBrahma/react-native-shadow-2#71]
Hello, is it possible to implement inner shadow with this package?
If yes please tell how can I work with it
Thanks  🙌🏻

**Comment by SrBrahma** [comment]
Can you give me a visual example of what you want?

**Comment by Ali-Oliaee** [comment]
sure,  there are some examples
<img width="681" alt="image" src="https://user-images.githubusercontent.com/79130209/234381891-ff2ef729-e149-49ea-be0a-16676e45598a.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/79130209/234381941-f8bc8cab-0143-4a47-9051-4b492587d7d7.png">

**Comment by SrBrahma** [comment]
Hmm this seems quite oval. I don't believe is doable as with the SVG's round gradient we can only do 90 degrees borders. As far as I can notice, this seems to be some sort of overlay/clipping/mask that is darkening not only the inner part but the outline and the external part.

Also, this has no gradient; the darkening is applied with a constant color along its distance.

You may try to accomplish this with the [ClipPath](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#clippath) or [Mask](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#mask).

Sorry if I got what you want wrong, but by the example I don't see what my library can do to accomplish it and this seems quite a very particular case.

Please, let me know if I got it wrong and if you know to explain it better, or to send me another example!

**Comment by Ali-Oliaee** [comment]
I saw the links you sent and unfortunately I don't have Svgs here to change the codes
I solved this problem with your library and the linear gradient library, the result is not exactly as designed but it gets the job done for me.
I put my code here, maybe it will help someone who is in the same situation as me

```
import {Shadow} from 'react-native-shadow-2';
import LinearGradient from 'react-native-linear-gradient';

...

 <Shadow
        distance={0}
        startColor={Colors.darkShadow}
        endColor={Colors.darkShadow}
        offset={[0, 1.5]}>
        <LinearGradient
          locations={[0.92, 0]}
          style={styles.innerShadow}
          colors={[Colors.lightningYellow, Colors.lightShadow]}>
          <TouchableOpacity activeOpacity={0.7} style={styles.submitButton}>
            <Text style={styles.submitButtonText}>{title}</Text>
          </TouchableOpacity>
        </LinearGradient>
      </Shadow>
```

thanks for your answer 🙏🏻
