### ISSUE TITLE
 Unable to find an element with testID

### ISSUE THREAD

**Issue by sokolovdm** [SrBrahma/react-native-shadow-2#74]
Hello. 
If i put children inside Shadow component, function render from '@testing-library/react-native' cant find element with testID.

**Comment by SrBrahma** [comment]
Please create a repository for me to try this and work on it.

**Comment by sokolovdm** [comment]
Just create component like this 
`
export const Card = React.memo<React.PropsWithChildren>(
    ({
        testID = 'Card'
    }) => {
        return (
            <Shadow
                startColor={'rgba(0, 0, 0, 0.02)'}
                distance={15}
                stretch>
                <View testID={testID}/>
            </Shadow>
        )
    },
)
`

and file test for them Card.spec.tsx

`
import React from 'react'
import { render } from '@testing-library/react-native'
import { Card } from './Card'
describe('Card', () => {
   it('Find View with testID=Card', () => {
        const { getByTestId } = render(<Card/>)
        const card = getByTestId('Card')
        expect(card).toBeDefined()
    })
})
`
npm run test
or 
npm run test Card.spec.tsx

and u will see something like this


     Unable to find an element with testID: Card

      22 |         const { getByTestId } = render(<Card />)
      23 |
    > 24 |         const card = getByTestId('Card')
         |                      ^
      25 |
      26 |         expect(card).toBeDefined()
      27 |     })

**Comment by SrBrahma** [comment]
@sokolovdm Care to investigate this issue? If you find the reason/the fix, it would help.
