### ISSUE TITLE
Can I do this effect with this library?

### ISSUE THREAD

**Issue by bolan9999** [SrBrahma/react-native-shadow-2#75]
![shadow](https://github.com/SrBrahma/react-native-shadow-2/assets/14797923/9aab6f10-01e1-4dc1-bef7-7e9747e6169e)

**Comment by SrBrahma** [comment]
The problem is here:

<img width="300" alt="image" src="https://github.com/SrBrahma/react-native-shadow-2/assets/28177550/ae2189c1-6822-4ccb-a843-cad8adbe82b4">

We don't do shadows that have this "negative radius" in this library. While it could be coded, I don't have plans on doing it.
