### ISSUE TITLE
Sides and corners

### ISSUE THREAD

**Issue by dotoff** [SrBrahma/react-native-shadow-2#76]
the syntax for applying shadow only to specific sides are confusing, i'm trying to get a neumorphic effect by coupling two different shadows one for left and top corners, and the other for bottom and right corners, but i cant seem to figure out how to apply them, sorry for the dumb question

**Comment by m4tt86** [comment]
@dotoff  you are right, I have the same problem. I don't know how to use it

**Comment by SrBrahma** [comment]
Hi, in the README we have this:

<img width="631" alt="image" src="https://github.com/SrBrahma/react-native-shadow-2/assets/28177550/3127f2fd-1cc4-4d0c-a0c4-7cb57fd4bb38">

But I understand it may not be clear as `Record` is a Typescript concept/type.

Basically, if you want only the **topEnd** corner to be drawn (same as **topRight**, with the RTL naming we use in this lib), you need to disable all the other ones. You do that by:

```tsx
<Shadow
  ...
  corners={{ topStart: false, bottomStart: false, bottomEnd: false }}
>
```

As said in the image, we don't need to specify the `topEnd` as it defaults to true.

If it doesn't have the expected output, please let me know.

Also, please let me know how the README could be improved for others that would fall in the same doubt! I will leave a link in both properties' description to this comment in the meantime.
