### ISSUE TITLE
Corners/sides types should allow Partial

### ISSUE THREAD

**Issue by justjooshing** [SrBrahma/react-native-shadow-2#83]
Firstly, thank you for writing this library, and I apologise if I'm not using it correctly. I've just found it after trying to make shadows work on android - this has helped a lot :) 

From your comment [here](https://github.com/SrBrahma/react-native-shadow-2/issues/76) it looks as if we can omit properties and they will default to `true`, but currently typescript complains if not all of the properties for corners or sides are specified. 

The current type definition means that all keys in the record must be defined, wrapping `Record<>` in `Partial<>` will stop TS complaining when only some are defined

    corners?: Record<'topStart' | 'topEnd' | 'bottomStart' | 'bottomEnd', boolean>;
    sides?: Record<'start' | 'end' | 'top' | 'bottom', boolean>;

    corners?: Partial<Record<'topStart' | 'topEnd' | 'bottomStart' | 'bottomEnd', boolean>>;
    sides?: Partial<Record<'start' | 'end' | 'top' | 'bottom', boolean>>;

**Comment by SrBrahma** [comment]
Fixed on 7.1.1 ;)
