### ISSUE TITLE
Does React Native 0.76 replace this library?

### ISSUE THREAD

**Issue by g-otn** [SrBrahma/react-native-shadow-2#86]
Very recently the React Native team [announced](https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#box-shadow-and-filter-style-props) the new `boxShadow` and `filter` props in version 0.76.0, which mimics web behavior.

For newer projects, is there a use case where this library would be better than using the props directly? Sorry if this is not the right place to ask.

I've been using this library in my project and was considering migrating.

**Comment by SrBrahma** [comment]
Hi!

Yes, this new prop seems to be a better solution than this lib! Finally there is a vanilla solution for it!

**Comment by g-otn** [comment]
That's nice to hear! Thanks for maintaining this library in the meanwhile!

**Comment by g-otn** [comment]
Maybe something should be announced in the README?

**Comment by SrBrahma** [comment]
Done! Thanks, @g-otn!
