### ISSUE TITLE
Shadow getting weird in IOS app on Testflight. 

### ISSUE THREAD

**Issue by code-with-shahzad** [SrBrahma/react-native-shadow-2#87]
I applied shadow on my fewer components which is working fine on local, but when I upload my app to testflight it's getting some red weird background with some white text. see my attachment please.

My code 
`<TouchableOpacity activeOpacity={1}>
     <Shadow distance={1} style={{ borderRadius: 100 }} startColor={"#0000001a"} offset={[1, 1]}>
         <View style={styles.addCharacter}>
             <Text style={[styles.baseText, { fontWeight: "bold" }]}>Add a Character</Text>
        </View>
     </Shadow>
  </TouchableOpacity>`
<img width="98" alt="image" src="https://github.com/user-attachments/assets/461e7e33-1fc8-47cf-9014-8f19d7f70ccc" />
<img width="263" alt="image" src="https://github.com/user-attachments/assets/a4b7d388-7e8f-4a05-a26e-6650e4b299e2" />

**Comment by SrBrahma** [comment]
This is very strange. Are you using React Native or Expo?

**Comment by code-with-shahzad** [comment]
I am using Expo

**Comment by SrBrahma** [comment]
This white text might give us some clues. Can you make the shadow very large without a component on top of it so we can read what it says?

**Comment by code-with-shahzad** [comment]
The app is being test by the clients and i can't add the shadow again right now. But yeah I will do something so you will get some idea why this is happening.

**Comment by SrBrahma** [comment]
You might want to instead use the new React Native's shadow instead, as I don't have much plans to keep this library anymore as this new built-in solution is apparently just better overall. Check initial block on the README about it!

**Comment by SrBrahma** [comment]
You might want to instead use the new React Native's shadow instead, as I don't have many plans to keep this library anymore as this new built-in solution is apparently just better overall. Check initial block on the README about it!

**Comment by code-with-shahzad** [comment]
yeah sure am using the react native's shadow now. thanks
