### ISSUE TITLE
Create shadow without height and width on 1st render

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [SrBrahma/react-native-shadow-2#9]
How to create shadow without height and width on first render. Second render onLayout, even we tried but the effect was not good.

Can you please suggest the solution. Can you implement it?

**Comment by SrBrahma** [comment]
I started to work on that right now! Cross your fingers! :crossed_fingers: :sweat_smile:

**Comment by SrBrahma** [comment]
Implemented in #11, version 3.0.0! Please, read the new README, try it out and report any bug!
